name: chaboo
description: "Kitap takas uygulaması."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'


#------------------ PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.3.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  lottie: ^2.2.0
  smooth_page_indicator: ^1.2.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Product Specific


  #--------------------- ./ PACKAGE END ---------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  #--------------------- LOCAL ASSETS ---------------------#
  assets:

    - assets/icons/icon.png
    - assets/logos/icon.png
    - assets/images/onboarding_images/Animation1.json
    - assets/images/onboarding_images/Animation2.json
    - assets/images/onboarding_images/Animation3.json
    - assets/images/onboarding_images/Animation4.json
    - assets/images/onboarding_images/Animation5.json
    - assets/images/onboarding_images/Animation6.json


  #--------------------- LOCAL FONTS ---------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

