// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0W6Od0vWTgedGjoVkgXiORw_BS58Vc7Q',
    appId: '1:408724382221:android:a5495df15261aab38e6b44',
    messagingSenderId: '408724382221',
    projectId: 'chaboo-77e07',
    storageBucket: 'chaboo-77e07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxmw-CAqR8rjDFMYftWx5cPSui-4Bgp5s',
    appId: '1:408724382221:ios:c58701a768d5b9238e6b44',
    messagingSenderId: '408724382221',
    projectId: 'chaboo-77e07',
    storageBucket: 'chaboo-77e07.appspot.com',
    androidClientId: '408724382221-mt5fssjrt0mhnf0u6ivlk45mcesqumpu.apps.googleusercontent.com',
    iosClientId: '408724382221-dnedpduroep7im8pahgik2hqsuajfvlk.apps.googleusercontent.com',
    iosBundleId: 'com.chaboo.chaboo',
  );

}